<section class="content-block" role="main">
    <article class="data-block nested">
    <header>
                                <h2>Form Client</h2>
                                <ul class="data-header-actions tabs">
                                    <li class="demoTabs active"><a href="#horizontal">Gestion client</a></li>
                                    <li class="demoTabs"><a href="#vertical">Gestion projet</a></li>
                                    <li class="demoTabs"><a href="#advanced">Payement De projet</a></li>
                                </ul>
                            </header>
                            <section class="tab-content">
                            
                                <!-- Example horizontal forms -->
                                <!-- Tab #horizontal -->
                                <div class="tab-pane active" id="horizontal">
                                
                                    <form class="form-horizontal" method="post">
                                        <fieldset>
                                            <legend>Form Client</legend>
                                            <div class="control-group">
                                                <label class="control-label" for="input" >Nom Client</label>
                                                <div class="controls">
                                                    <input  name="nom" class="input-xlarge" type="text" 
                                                     value="<?php echo $this->nom;?>" required >
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label" for="input" >Prenom Client</label>
                                                <div class="controls">
                                                    <input  name="prenom" class="input-xlarge" type="text" 
                                                     value="<?php echo $this->prenom;?>" required >
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label" for="input" >Adresse Client</label>
                                                <div class="controls">
                                                    <input  name="adresse" class="input-xlarge" type="text" 
                                                     value="<?php echo $this->adresse;?>" required>
                                                </div>
                                            </div>
                                        <div class="nav" >
                                            <ul>
                                                <li>
                                            <div class="form-actions">
                        <button class="btn btn-alt btn-large btn-primary" type="submit">modifier</button>
                        </div>
                                            </li>   
                                            </ul>
                                        </div>
                                                               
                                          </fieldset>
                                       </form>
                                   </div>
                                </section>
    </article>
    </section>