 <section class="content-block" role="main">
    <article class="data-block nested">
    	
                            <section class="tab-content">
                         
                                <div class="tab-pane active" id="horizontal">
                                
                                    <form class="form-horizontal">
                                        <fieldset>
                                            <legend>Book's Form</legend>
                                        
                                        <h3>Liste of Books</h3>
                                        <table class="table">
                                            <thead>
      
                                                 <tr>
                                                  
                                                     <th>book's Matiere</th>
                                                     <th>date</th>
                                                     <th>book's NAme</th>
                                                     <th>Description</th>
                                                     <th>action</th>
                                                 </tr>
                                             </thead>
                                             
                                         </table>



                    
                    
                           
                    <div class="nav" >
                                            <ul>
                                           
                                                  <li>
                                            <div class="form-actions">
                        <button class="btn btn-alt btn-large btn-primary" type="submit">Modifier</button>
                        </div>
                                            </li>
                                                    <li>
                                            <div class="form-actions">
                        <button class="btn btn-alt btn-large btn-primary" type="submit">Supprimer</button>
                        </div>
                                            </li>
                                         
                                            </ul>
                                        </div>                  
                                          </fieldset>
                                       </form>
                                   </div>
                                </section>
    </article>
    </section>
