 <section class="content-block" role="main">
    <article class="data-block nested">
    <header>
                                <h2>Form Client</h2>
                                <ul class="data-header-actions tabs">
                                    <li class="demoTabs active"><a href="#horizontal">Gestion client</a></li>
                                    <li class="demoTabs"><a href="#vertical">Gestion projet</a></li>
                                    <li class="demoTabs"><a href="#advanced">Payement De projet</a></li>
                                </ul>
                            </header>
                            <section class="tab-content">
                            
                                <!-- Example horizontal forms -->
                                <!-- Tab #horizontal -->
                                <div class="tab-pane active" id="horizontal">
                                
                                    <form class="form-horizontal">
                                        <fieldset>
                                            <legend>Form Projet</legend>
                                        
                                        <h3>Liste Des projet</h3>
                                        <table class="table">
                                            <thead>
      
                                                 <tr>
                                                  
                                                     <th>Type projet</th>
                                                     <th>date debut projet</th>
                                                     <th>date fin projet</th>
                                                     <th>nom client</th>
                                                     <th>Action</th>
                                              
                                                 </tr>
                                             </thead>
                                         </table>



                    
                    
                           
                    <div class="nav" >
                                            <ul>
                                           
                                                  <li>
                                            <div class="form-actions">
                        <button class="btn btn-alt btn-large btn-primary" type="submit">Modifier</button>
                        </div>
                                            </li>
                                                    <li>
                                            <div class="form-actions">
                        <button class="btn btn-alt btn-large btn-primary" type="submit">Supprimer</button>
                        </div>
                                            </li>
                                         
                                            </ul>
                                        </div>                  
                                          </fieldset>
                                       </form>
                                   </div>
                                </section>
    </article>
    </section>
